site_name: Notas Musicais
repo_url: https://github.com/will951357/notas-musicais
edit_uri: tree/master/docs
theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css

watch:
  - notas_musicais

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - notas_musicais